### ISSUE TITLE
MyHealth.Web missing wwwroot

### ISSUE THREAD

**Issue by AbdouSlayne** [Microsoft/HealthClinic.biz#11]
Hello,

When open the solution 01_Demos_ASPNET5, I cant publish the web project to Azure, due to the missing wwwroot folder.
Here is the screenshot from the Wiki page deployement to Azure :
![alt text](https://github.com/alinapopa/Images/raw/master/HealthClinicWiki/Deployment/image8.png "")

And this is what I got when I open it in my environnement :
<img width="277" alt="healthissue" src="https://cloud.githubusercontent.com/assets/7440727/13639080/52e80bc8-e60f-11e5-99b4-62bafb58ced2.png">

Even when I brows the GitHub source code here, I dont see any wwwroot forlder :
<img width="503" alt="healthissue2" src="https://cloud.githubusercontent.com/assets/7440727/13639135/968d1c7e-e60f-11e5-92ef-a0415c750cb1.png">

Any help ?

Thank you.

**Comment by ibonilm** [comment]
Sync to repo and try again please

**Comment by AbdouSlayne** [comment]
Thanks, it's good now.
