### ISSUE TITLE
AADSettings?

### ISSUE THREAD

**Issue by Onjay** [Microsoft/HealthClinic.biz#12]
The Native Desktops apps appears to require Azure Active Directory credentials in order to build. Should I set this up under my Default Active Directory, or would it make more sense to create a new active directory?
I used the 10_Demos_Deployment to deploy to Azure, but I don't see the credentials anywhere so I'm assuming I need to create them in Active Directory by adding an app?

Exception thrown: 'System.UriFormatException' in System.dll
Exception thrown: 'System.TypeInitializationException' in MyHealth.Client.Core.dll
Exception thrown: 'Autofac.Core.DependencyResolutionException' in Autofac.dll
Exception thrown: 'Autofac.Core.DependencyResolutionException' in Autofac.dll

 static SecuritySettings AADSettings = new SecuritySettings()
        {
            ClientId = "YOUR_AAD_CLIENT_ID",
            RedirectUri = new Uri("YOUR_AAD_REDIRECT_URI"),
            Authority = "YOUR_AAD_AUTHORITY",
            Scope = "https://graph.microsoft.com",
            Domain = "YOUR_AAD_DOMAIN"
        };

**Comment by ibonilm** [comment]
WPF doesn´t requiere AAD authentication. It was a bug in the default information.

Please, sync the repo and try again. I have update the AppSettings.cs file.

**Comment by Onjay** [comment]
That worked Ibonilm!
