### ISSUE TITLE
Shouldn't this just compile, or am I missing something?

### ISSUE THREAD

**Issue by samcov** [Microsoft/HealthClinic.biz#19]
Here's what I get(see pic)
![healtherrors](https://cloud.githubusercontent.com/assets/1551314/20459666/cb265f44-ae7e-11e6-97b6-9e79bc606d73.jpg)

**Comment by ibonilm** [comment]
The app is tokenized. Before building the solution you must configure the tokens with the right values in the AppSettings.cs file. 

You should deploy the backend services in your azure subscription and get the patientId and tenantId values. In the wiki you can find information about how to deploy the ASPNET5 app.

**Comment by samcov** [comment]
Thanks.
