### ISSUE TITLE
Does this project build using the latest version of Core and Visual Studio?

### ISSUE THREAD

**Issue by johntallon** [Microsoft/HealthClinic.biz#21]
Hi folks,

I took down this project and its not building meaning I have a lot of reference and package problems. Is this project being maintained? 

Regards

**Comment by CESARDELATORRE** [comment]
I don't think it is maintained. This was about the demos for VS 2015 and it is owned by VS Marketing. This is a frozen version of VS2015 timeframe.
For latest reference apps on Microservices and Containers and mobile Xamarin, look at GitHub for eShopOnContainers.
For plain ASP.NET Core Architecture and reference look at eShopOnWeb.
Also here you have the latest Guides/eBooks:

Http://dot.net/Architecture

**Comment by johntallon** [comment]
Thanks Cesar. Will follow these links.
