### ISSUE TITLE
Error while adding HealthClinicbiz project to VSTS

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/HealthClinic.biz#5]
Hi there,

I am trying out the devops on HealthClinicbiz project on VSTS. But unfortunately i can't map the workspace directory since the project exceeds the 260 characters of the filenames. Can anyone suggest me here?

Regards,
Srivatsa

**Comment by ibonilm** [comment]
We also have the build definitions in VSTS connected to GitHub. Which kind of build definitions are you using? The workflow one or the new one? If you are using the new one...in which directory is your agent working directory? I install it in "c:\agent" not to have too long after cloning the repo.

**Comment by SrivatsaMarichi** [comment]
Sorry for the confusion here. I meant i wasn't able to add the project from my local drive to Team Project in VSTS.

**Comment by ibonilm** [comment]
If you can, you could use VSTS with git instead of TFVC.

**Comment by SrivatsaMarichi** [comment]
PFA screenshot



![2016-01-28_1913](https://cloud.githubusercontent.com/assets/13433045/12645969/6e666df4-c5f3-11e5-87aa-c344a284ddbf.png)

**Comment by ibonilm** [comment]
After cloning from GitHub have you open or build any solution? Some of them have npm dependencies that Visual Studio restarts automatically. Check if you have any "node_modules" directory & try to remove it. 

Of course, you can clone again the repo from GitHub to be sure that is clean and try to upload to your VSTS again. I think that you could also use the "git clean -dfx" command to remove the files/directories that are not also in GitHub.

**Comment by SrivatsaMarichi** [comment]
Cool. Thank you, let me try and get back to you...

Thanks,Srivatsa 

    On Thursday, 28 January 2016 7:22 PM, Ibon Landa <notifications@github.com> wrote:
 

 After cloning from GitHub have you open or build any solution? Some of them have npm dependencies that Visual Studio restarts automatically. Check if you have any "node_modules" directory & try to remove it. Of course, you can clone again the repo from GitHub to be sure that is clean and try to upload to your VSTS again. I think that you could also use the "git clean -dfx" command to remove the files/directories that are not also in GitHub.—
